### PR TITLE
feat: ability to set custom message resolvers

### PR DESCRIPTION
**Pull request by rajiteh**
I wanted to be able to set values other than just `Message().Text` like Location, etc

This was the fastest way to add that in, basically by enhancing the input class, however if you think of better ways let me know!

### CODE REVIEW

**Comment by rusq** [comment]
Hey, @rajiteh thanks for the PR,

That's a good suggestion! The only comment I'd have - instead of "SetValueResolver" function, could you make an Option, i.e. IOptValueResolver, pretty much like [this](https://github.com/rusq/tbcomctl/pull/13/files#diff-8ef97170810c3ede0de2d34df9b1656ec156498c289d7ab2dea5ed8c28e92acdR45)?

**Comment by rusq** [comment]
Also, did you know that[ telebot v3](https://github.com/tucnak/telebot) is out?

**Comment by rajiteh** [comment]
Made it an input option as you suggested! Thx
Re: telebot v3, yes, I did notice that. However, I'm pretty new to bot writing and just happened to find your library when I was looking for stateful conversation support for telebot. Did I miss something? 😳

**Review by rusq — APPROVED** [review]

**Comment by rusq** [comment]
Hey @rajiteh , thanks for the code update.  Yeah, telebot.v3 is quite different in a way that there's a universal handler function that handles `Context` interface instead of individual types, i.e. `*tele.Message`, `*tele.Callback`.  I suggest you to have a look - there's also a [Telegram Group with discussion](https://t.me/go_telebot) that you can join.

**Pull request merged**
